/*
 *    Copyright 2012 Luca Tagliani
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package com.github.lucapino.mp3catalog.view;

import ca.odell.glazedlists.swing.EventJXTableModel;
import com.github.lucapino.mp3catalog.model.HibernateUtil;
import com.github.lucapino.mp3catalog.model.Song;
import java.io.File;
import javax.swing.JTable;
import org.hibernate.Session;
import org.hibernate.Transaction;
import org.jaudiotagger.audio.AudioFile;
import org.jaudiotagger.audio.AudioFileIO;
import org.jaudiotagger.tag.FieldKey;
import org.jaudiotagger.tag.Tag;

/**
 *
 * @author luca
 */
public class PropertiesJPanel extends javax.swing.JPanel {

    private static int TITLE = 0;
    private static int AUTHOR = 1;
    private static int ALBUM = 2;
    private String[] oldValues = new String[7];
    private Song editedSong = null;
    private JTable mainTable;

    /**
     * Creates new form PropertiesJPanel
     */
    public PropertiesJPanel(JTable mainTable) {
        initComponents();
        this.mainTable = mainTable;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        titleTextField = new javax.swing.JTextField();
        albumTextField = new javax.swing.JTextField();
        albumLabel = new javax.swing.JLabel();
        authorTextField = new javax.swing.JTextField();
        authorLabel = new javax.swing.JLabel();
        durationTextField = new javax.swing.JTextField();
        durationLabel = new javax.swing.JLabel();
        bitrateTextField = new javax.swing.JTextField();
        bitrateLabel = new javax.swing.JLabel();
        filesizeTextField = new javax.swing.JTextField();
        filesizeLabel = new javax.swing.JLabel();
        filenameTextField = new javax.swing.JTextField();
        filenameLabel = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        songNumberLabel = new javax.swing.JLabel();
        songNumberTextField = new javax.swing.JTextField();

        setToolTipText("Properties");

        titleLabel.setText("Titolo");

        albumLabel.setText("Album");

        authorLabel.setText("Artista");

        durationTextField.setEnabled(false);

        durationLabel.setText("Durata");

        bitrateTextField.setEnabled(false);

        bitrateLabel.setText("Bitrate");

        filesizeTextField.setEnabled(false);

        filesizeLabel.setText("Dimensione");

        filenameTextField.setEnabled(false);

        filenameLabel.setText("Nome file");

        resetButton.setText("Reset");
        resetButton.setEnabled(false);
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.setEnabled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        songNumberLabel.setText("Song number");

        songNumberTextField.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel)
                    .addComponent(albumLabel)
                    .addComponent(authorLabel)
                    .addComponent(durationLabel))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(durationTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addComponent(authorTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addComponent(albumTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addComponent(titleTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filesizeLabel)
                    .addComponent(bitrateLabel)
                    .addComponent(filenameLabel)
                    .addComponent(songNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filenameTextField)
                    .addComponent(bitrateTextField)
                    .addComponent(filesizeTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(songNumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {resetButton, saveButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bitrateLabel)
                            .addComponent(bitrateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filesizeLabel)
                            .addComponent(filesizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filenameLabel)
                            .addComponent(filenameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resetButton)
                            .addComponent(saveButton)
                            .addComponent(songNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titleLabel)
                            .addComponent(titleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(albumLabel)
                            .addComponent(albumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(authorLabel)
                            .addComponent(authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(durationLabel)
                            .addComponent(durationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(songNumberLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // reset old values
        titleTextField.setText(oldValues[TITLE]);
        authorTextField.setText(oldValues[AUTHOR]);
        albumTextField.setText(oldValues[ALBUM]);
    }//GEN-LAST:event_resetButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // synch textfield with song
        editedSong.setTitle(titleTextField.getText());
        editedSong.setArtist(authorTextField.getText());
        editedSong.setAlbum(albumTextField.getText());
        Session session = HibernateUtil.getSessionFactory().openSession();
        Transaction tx = session.beginTransaction();
        session.update(editedSong);
        tx.commit();
        // update the field in file
        try {
            AudioFile audioFile = AudioFileIO.read(new File(filesizeTextField.getText()));
            Tag tag = audioFile.getTag();
            tag.setField((FieldKey.TITLE), editedSong.getTitle());
            tag.setField((FieldKey.ARTIST), editedSong.getTitle());
            tag.setField((FieldKey.ALBUM), editedSong.getTitle());
            audioFile.commit();
        } catch (Exception ex) {
        }
        // update model
        EventJXTableModel<Song> model = (EventJXTableModel) mainTable.getModel();
        int row = mainTable.getSelectedRow();
        model.fireTableRowsUpdated(row, row);
    }//GEN-LAST:event_saveButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel albumLabel;
    public javax.swing.JTextField albumTextField;
    public javax.swing.JLabel authorLabel;
    public javax.swing.JTextField authorTextField;
    public javax.swing.JLabel bitrateLabel;
    public javax.swing.JTextField bitrateTextField;
    public javax.swing.JLabel durationLabel;
    public javax.swing.JTextField durationTextField;
    public javax.swing.JLabel filenameLabel;
    public javax.swing.JTextField filenameTextField;
    public javax.swing.JLabel filesizeLabel;
    public javax.swing.JTextField filesizeTextField;
    public javax.swing.JButton resetButton;
    public javax.swing.JButton saveButton;
    public javax.swing.JLabel songNumberLabel;
    public javax.swing.JTextField songNumberTextField;
    public javax.swing.JLabel titleLabel;
    public javax.swing.JTextField titleTextField;
    // End of variables declaration//GEN-END:variables

    public Song getEditedSong() {
        return editedSong;
    }

    public void setEditedSong(Song editedSong) {
        this.editedSong = editedSong;
    }
}
